### ISSUE TITLE
feature request: control naming of version tag (omit ' v' prefix) 

### ISSUE THREAD

**Issue by mu88** [versionize/versionize#110]
Hi 👋🏻

First of all, thank you for your amazing project! I added it yesterday to a couple of my projects and it works very well 👏🏻

One thing that I stumbled upon was using the Git tag created by versionize as Docker image tag and the tag's `v` prefix. For example, let's assume calling `dotnet versionize` creates a new Git tag `v3.0.0`. Now when creating a Docker image for this release via GitHub Actions, I have to shorten the Git tag like this so that my final image is tagged `mu88/raspifancontroller:3.0.0` instead of `mu88/raspifancontroller:v3.0.0` (which would happen when using `${{ github.ref_name }}`):
```yaml
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Build Docker and Push
      run: dotnet publish RaspiFanController/RaspiFanController.csproj --os linux --arch arm64 /t:PublishContainer '-p:ContainerImageTags="${{ env.VERSION }};latest"'
```

Since I had to insert this snippet into each of my Release pipeline, it would be cool if I could instruct versionize to create a Git tag without the `v` prefix (i. e. `3.0.0` instead of `v3.0.0`).
