### ISSUE TITLE
Azure Release Pipeline

### ISSUE THREAD

**Issue by shabirjan** [versionize/versionize#3]
Hi

Thanks for such awesome tool, But is it possible to use this in my Release pipeline as task?

**Comment by iangregsondev** [comment]
I would also be interested in this, did you manage to find out ?

**Comment by nerdybynature** [comment]
I made it work in a POC pipeline by having two tasks:

```yml
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'update Versionize -g'

- task: PowerShell@2
  displayName: 'Versionize'
  inputs:
    targetType: 'inline'
      script: |
        versionize --skip-dirty --skip-commit
```

**Comment by volkanpaksoy** [comment]
@nerdybynature Thanks for the snippet. I'm in a similar situation (just using AWS pipeline). Just wondering: Are you also pushing tags to master branch as shown in the documentation "git push --follow-tags origin master"

For me to achieve this, I would need to create a new SSH key every time the pipeline runs and I would have to delete the key from AWS after it's pushed the code. This sounds a bit excessive to me but I cannot figure out another way. If I don't push I cannot keep incrementing the version.

How did you handle this situation?

**Comment by nerdybynature** [comment]
@volkanpaksoy 

Yes, I've managed to do it the following way.
_(I run a forked and modified version of the tool but that shouldn't be an issue.)_

```yml
steps:
- task: DotNetCoreCLI@2
  displayName: Install Versionize Tool
  inputs:
    command: custom
    custom: tool
    arguments: 'update -g Forked.Versionize --ignore-failed-sources --add-source { my nuget feed url }'

- script: |
    git config --global user.email "pipeline.bot@example.com"
    git config --global user.name "pipeline-bot"
    versionize-forked --skip-dirty
  displayName: "Run Versionize"
```

The important part is the `git config` commands just before running the tool.

Then at the end of our pipeline I run:

```yml
steps:
- task: PowerShell@2
  displayName: 'Git push changes and version tag'
  inputs:
    targetType: 'inline'
    script: |
      $pushUrl = "$(Build.Repository.Uri)".Substring("$(Build.Repository.Uri)".IndexOf("@dev.azure.com"))
      git push https://$(System.AccessToken)$pushUrl --follow-tags HEAD:master

```
End result:
![image](https://user-images.githubusercontent.com/1333979/109467097-f4603580-7a6a-11eb-8688-eef8ebbbc2e0.png)
