### ISSUE TITLE
Any example for GitLab CI/CD ?

### ISSUE THREAD

**Issue by tgiachi** [versionize/versionize#97]
Hi!,
Anyone have any example for integrate versionize in GitLab CD/CI ?
Thanks!

**Comment by cabauman** [comment]
Sorry, I'm not familiar with GitLab. Are you not able to find GitLab pipeline examples online? Using versionize in GitLab should be the same as running any other CLI tool in GitLab, I assume. Are you running into issues with your attempts?

**Comment by gsroberts** [comment]
I'm a bit late to the party, but here's the pipeline job my company has been successfully using for a while now:

```yaml
build_app:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim
  needs: []
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0
  script:
    - git remote set-url origin https://${CI_TOKEN_NAME}:${CI_TOKEN}@gitlab.com/group/project.git
    - dotnet tool restore
    # Check if shallow repo and correct it if it is since versionize needs an unshallow repo
    - if $(git rev-parse --is-shallow-repository); then echo 'Repo is shallow and needs to be fixed. Calling fetch with --unshallow'; git fetch --unshallow; fi
    # cut release only for default branch
    - if [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then dotnet tool run versionize && git push --follow-tags origin HEAD:master; else echo 'Release will not be cut and image will not be built because this is not the default branch for the repo'; fi
    - dotnet publish "Project/Project.csproj" -c Release -o publish_output
    # ensure we get the latest version from versionize, called here in the event a release was triggered
    - dotnet tool run versionize inspect
    - VERSION=`dotnet tool run versionize inspect`
    - echo "$VERSION" > .version
    - echo "Build complete for version $VERSION of the dotnet application"
  artifacts: 
    name: "publish_output"
    paths:
      - publish_output/
      - .version
    expire_in: 1 week
```

We then use that job's output to create a container image that is deployed into k8s.

Also, we only run `versionize` on merges into the default branch but that's not strictly necessary if you don't use feature branches and merge requests to get code into your default branch.

Note that we specifically check the repo to see if it's shallow because the GitLab CI pipeline has proven to be a little flaky in that regard, resulting in random job failures.
